export const GET_CONTACTS = "GET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Users
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const USER_ERROR = "USER_ERROR";

// Specialist
export const GET_SPECIALISTS = "GET_SPECIALISTS";
export const GET_SPECIALIST = "GET_SPECIALIST";
export const ADD_SPECIALIST = "ADD_SPECIALIST";
export const DELETE_SPECIALIST = "DELETE_SPECIALIST";
export const UPDATE_SPECIALIST = "UPDATE_SPECIALIST";
export const CLEAR_SPECIALISTS = "CLEAR_SPECIALISTS";
export const SPECIALIST_ERROR = "SPECIALIST_ERROR";
